// Decompiled with JetBrains decompiler
// Type: pdfFiller.Model.Amplitude.AutoGeneratedAmplitudeRestInterface
// Assembly: pdfFiller, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: AEBF2585-E3E0-4E31-BEF4-9C2E935A9144
// Assembly location: D:\pdfFiller\pdfFiller.exe

using pdfFiller.Model.Pojo.Response;
using pdfFiller.RefitInternalGenerated;
using Refit;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Net.Http;
using System.Reflection;
using System.Threading.Tasks;

#nullable disable
namespace pdfFiller.Model.Amplitude;

[ExcludeFromCodeCoverage]
[DebuggerNonUserCode]
[Preserve]
[Obfuscation(Exclude = true)]
internal class AutoGeneratedAmplitudeRestInterface : AmplitudeRestInterface
{
  private readonly IRequestBuilder requestBuilder;

  public HttpClient Client { get; protected set; }

  public AutoGeneratedAmplitudeRestInterface(HttpClient client, IRequestBuilder requestBuilder)
  {
    this.Client = client;
    this.requestBuilder = requestBuilder;
  }

  Task<AmplitudeResponse> AmplitudeRestInterface.SendEvents(Dictionary<string, object> body)
  {
    object[] objArray = new object[1]{ (object) body };
    return (Task<AmplitudeResponse>) this.requestBuilder.BuildRestResultFuncForMethod("SendEvents", new Type[1]
    {
      typeof (Dictionary<string, object>)
    })(this.Client, objArray);
  }
}
